name: Unit tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: pom.xml
          distribution: 'temurin'
      - name: Build and run unit tests
        run: mvn verify
