name: Unit tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: pom.xml
          distribution: 'temurin'
      - run: mvn package
      - name: Build and run unit tests
        run: mvn verify
      - name: Run debug mode for default-v3
        run: java -jar target/TankGame-*.jar --debug default-v3
      - name: Run debug mode for default-v4
        run: java -jar target/TankGame-*.jar --debug default-v4
